import { type Locale } from './replies';

/**
 * French and Spanish shopping requests for the offline parser (ADR-0009). The local driver only
 * knows the English shopping vocabulary, so a French or Spanish request is first rewritten into
 * the English words it means ("ordinateur portable pour coder moins de 1 500 $" → "laptop for
 * coding under $1500"). Unknown words pass through. English requests are never touched.
 *
 * Keys are written without accents: the request is matched with its accents removed, so
 * "ecran" and "écran" both work.
 */
const PHRASES: Record<string, string> = {
  // ── Budget (French) ──
  'pas plus de': 'no more than',
  'pas plus que': 'no more than',
  'moins cher que': 'cheaper than',
  'moins chere que': 'cheaper than',
  'moins chers que': 'cheaper than',
  'moins cheres que': 'cheaper than',
  'moins de': 'under',
  'en dessous de': 'under',
  'au-dessous de': 'under',
  'jusqu a': 'up to',
  'au maximum': 'max',
  'au plus': 'max',
  maximum: 'max',
  'au moins': 'at least',
  'plus de': 'over',
  'au-dessus de': 'over',
  environ: 'around',
  'autour de': 'around',
  'aux alentours de': 'around',
  'budget de': 'budget of',
  'pas cher': 'cheap',
  'pas chere': 'cheap',
  'pas chers': 'cheap',
  'pas cheres': 'cheap',
  'bon marche': 'cheap',
  economique: 'cheap',
  abordable: 'affordable',
  entre: 'between',
  // ── Budget (Spanish) ──
  'no mas de': 'no more than',
  'mas barato que': 'cheaper than',
  'mas barata que': 'cheaper than',
  'mas baratos que': 'cheaper than',
  'mas baratas que': 'cheaper than',
  'por menos de': 'under',
  'menos de': 'under',
  'por debajo de': 'under',
  hasta: 'up to',
  'como maximo': 'max',
  maximo: 'max',
  'mas de': 'over',
  'por encima de': 'over',
  'al menos': 'at least',
  'por lo menos': 'at least',
  'alrededor de': 'around',
  'cerca de': 'around',
  aproximadamente: 'around',
  'presupuesto de': 'budget of',
  presupuesto: 'budget',
  barato: 'cheap',
  barata: 'cheap',
  baratos: 'cheap',
  baratas: 'cheap',
  economico: 'cheap',
  economica: 'cheap',
  economicos: 'cheap',
  asequible: 'affordable',
  dolares: 'dollars',

  // ── Product types ──
  'ordinateur portable': 'laptop',
  'ordinateurs portables': 'laptop',
  'pc portable': 'laptop',
  'pc portables': 'laptop',
  'ordi portable': 'laptop',
  'computadora portatil': 'laptop',
  'computadoras portatiles': 'laptop',
  'ordenador portatil': 'laptop',
  'ordenadores portatiles': 'laptop',
  portatil: 'laptop',
  portatiles: 'laptop',
  'ordinateur de bureau': 'desktop',
  'ordinateurs de bureau': 'desktop',
  'pc de bureau': 'desktop',
  'computadora de escritorio': 'desktop',
  'ordenador de sobremesa': 'desktop',
  'pc de escritorio': 'desktop',
  ordinateur: 'computer',
  ordinateurs: 'computer',
  ordi: 'computer',
  computadora: 'computer',
  computadoras: 'computer',
  ordenador: 'computer',
  ordenadores: 'computer',
  'grand ecran': 'large screen',
  'pantalla grande': 'large screen',
  ecran: 'screen',
  ecrans: 'screen',
  moniteur: 'monitor',
  moniteurs: 'monitor',
  pantalla: 'screen',
  pantallas: 'screen',
  casque: 'headphones',
  casques: 'headphones',
  ecouteurs: 'earbuds',
  ecouteur: 'earbuds',
  audifonos: 'headphones',
  auriculares: 'headphones',
  cascos: 'headphones',
  clavier: 'keyboard',
  claviers: 'keyboard',
  teclado: 'keyboard',
  teclados: 'keyboard',
  souris: 'mouse',
  raton: 'mouse',
  ratones: 'mouse',
  telephone: 'phone',
  telephones: 'phone',
  telefono: 'phone',
  telefonos: 'phone',
  celular: 'phone',
  celulares: 'phone',
  movil: 'phone',
  moviles: 'phone',
  'montre connectee': 'smartwatch',
  montre: 'watch',
  montres: 'watch',
  'reloj inteligente': 'smartwatch',
  reloj: 'watch',
  relojes: 'watch',
  enceinte: 'speaker',
  enceintes: 'speaker',
  'haut-parleur': 'speaker',
  'haut-parleurs': 'speaker',
  altavoz: 'speaker',
  altavoces: 'speaker',
  bocina: 'speaker',
  bocinas: 'speaker',
  parlante: 'speaker',
  parlantes: 'speaker',
  manette: 'controller',
  manettes: 'controller',
  mando: 'controller',
  mandos: 'controller',

  // ── Uses and qualities ──
  'jeux video': 'gaming',
  'jeu video': 'gaming',
  jeux: 'games',
  jeu: 'game',
  jouer: 'gaming',
  videojuegos: 'gaming',
  videojuego: 'gaming',
  juegos: 'games',
  juego: 'game',
  jugar: 'gaming',
  coder: 'coding',
  programmer: 'programming',
  programmation: 'programming',
  developpement: 'development',
  developpeur: 'developer',
  developpeuse: 'developer',
  programar: 'programming',
  programacion: 'programming',
  desarrollo: 'development',
  desarrollador: 'developer',
  desarrolladora: 'developer',
  codigo: 'code',
  travail: 'work',
  travailler: 'work',
  bureautique: 'office',
  trabajo: 'work',
  trabajar: 'work',
  oficina: 'office',
  voyage: 'travel',
  voyages: 'travel',
  voyager: 'travel',
  viaje: 'travel',
  viajes: 'travel',
  viajar: 'travel',
  'longs vols': 'long flights',
  'long vol': 'long flight',
  'long-courrier': 'long flights',
  'long-courriers': 'long flights',
  vols: 'flights',
  vol: 'flight',
  'vuelos largos': 'long flights',
  'vuelo largo': 'long flight',
  vuelos: 'flights',
  vuelo: 'flight',
  avion: 'plane',
  avions: 'plane',
  'plus leger': 'lighter',
  'plus legere': 'lighter',
  'mas ligero': 'lighter',
  'mas ligera': 'lighter',
  'mas liviano': 'lighter',
  leger: 'lightweight',
  legere: 'lightweight',
  legers: 'lightweight',
  legeres: 'lightweight',
  ligero: 'lightweight',
  ligera: 'lightweight',
  ligeros: 'lightweight',
  ligeras: 'lightweight',
  liviano: 'lightweight',
  liviana: 'lightweight',
  'plus silencieux': 'quieter',
  'plus silencieuse': 'quieter',
  'mas silencioso': 'quieter',
  'mas silenciosa': 'quieter',
  silencieux: 'quiet',
  silencieuse: 'quiet',
  silencieuses: 'quiet',
  silencioso: 'quiet',
  silenciosa: 'quiet',
  silenciosos: 'quiet',
  silenciosas: 'quiet',
  'sans ventilateur': 'fanless',
  'sin ventilador': 'fanless',
  'reduction de bruit': 'noise-cancelling',
  'reduction du bruit': 'noise-cancelling',
  'reduction de bruit active': 'noise-cancelling',
  'anti-bruit': 'noise-cancelling',
  antibruit: 'noise-cancelling',
  'cancelacion de ruido': 'noise-cancelling',
  'cancelacion activa de ruido': 'noise-cancelling',
  'cancelacion de ruido activa': 'noise-cancelling',
  'sans fil': 'wireless',
  inalambrico: 'wireless',
  inalambricos: 'wireless',
  inalambrica: 'wireless',
  inalambricas: 'wireless',
  'meilleure autonomie': 'long-lasting battery',
  'grande autonomie': 'long-lasting battery',
  'longue autonomie': 'long-lasting battery',
  'mayor duracion de bateria': 'long-lasting battery',
  'bateria de larga duracion': 'long-lasting battery',
  'larga duracion': 'long-lasting',
  autonomie: 'battery',
  batterie: 'battery',
  bateria: 'battery',
  confortable: 'comfortable',
  confortables: 'comfortable',
  comodo: 'comfortable',
  comoda: 'comfortable',
  comodos: 'comfortable',
  comodas: 'comfortable',
  ergonomique: 'ergonomic',
  ergonomiques: 'ergonomic',
  ergonomico: 'ergonomic',
  ergonomica: 'ergonomic',
  'course a pied': 'running',
  courir: 'running',
  correr: 'running',
  'salle de sport': 'gym',
  gimnasio: 'gym',
  'montage video': 'video editing',
  'retouche photo': 'photo editing',
  'edicion de video': 'video editing',
  'edicion de fotos': 'photo editing',
  creation: 'creative',
  creacion: 'creative',
  diseno: 'design',
  'plus grand': 'bigger',
  'plus grande': 'bigger',
  'mas grande': 'bigger',
  grand: 'large',
  grande: 'large',
  grandes: 'large',
  'memoire vive': 'RAM',
  memoire: 'memory',
  memoria: 'memory',
  stockage: 'storage',
  almacenamiento: 'storage',
  pouces: 'inch',
  pulgadas: 'inch',
  heures: 'hours',
  horas: 'hours',
  etudiant: 'student',
  etudiante: 'student',
  estudiante: 'student',
  cadeau: 'gift',
  regalo: 'gift',

  // ── Small words, rewritten to English ones the parser already ignores ──
  'quelque chose': 'something',
  algo: 'something',
  'il me faut': 'need',
  besoin: 'need',
  cherche: 'want',
  recherche: 'want',
  veux: 'want',
  voudrais: 'want',
  busco: 'want',
  quiero: 'want',
  necesito: 'need',
  'montre-moi': 'show me',
  'montrez-moi': 'show me',
  muestrame: 'show me',
  voir: 'show',
  ver: 'show',
  'la categorie': 'category',
  'la categoria': 'category',
  'en fait': 'actually',
  plutot: 'actually',
  'en realidad': 'actually',
  mejor: 'actually',
  pour: 'for',
  para: 'for',
  por: 'for',
  avec: 'with',
  con: 'with',
  sans: 'without',
  sin: 'without',
  un: 'a',
  une: 'a',
  uno: 'a',
  una: 'a',
  unos: 'some',
  unas: 'some',
  le: 'the',
  la: 'the',
  les: 'the',
  el: 'the',
  los: 'the',
  las: 'the',
  des: 'some',
  de: 'of',
  du: 'of',
  del: 'of',
  al: 'to',
  et: 'and',
  y: 'and',
  ou: 'or',
  o: 'or',
  mon: 'my',
  ma: 'my',
  mes: 'my',
  mi: 'my',
  mis: 'my',
  ton: 'your',
  ta: 'your',
  tes: 'your',
  votre: 'your',
  vos: 'your',
  tu: 'your',
  tus: 'your',
  su: 'your',
  sus: 'your',
  je: 'i',
  yo: 'i',
  qui: 'that',
  que: 'that',
  est: 'is',
  es: 'is',
  tres: 'very',
  muy: 'very',
  bon: 'good',
  bonne: 'good',
  bueno: 'good',
  buena: 'good',
  buen: 'good',
  nouveau: 'new',
  nouvelle: 'new',
  nuevo: 'new',
  nueva: 'new',
  dans: 'in',
  en: 'in',
  sur: 'on',
  sobre: 'on',
  plus: 'more',
  mas: 'more',
};

/** Words that only appear in French or Spanish requests: they mark one sent with an English header. */
const FOREIGN_MARKERS = new Set([
  'pour',
  'para',
  'avec',
  'moins',
  'menos',
  'ordinateur',
  'portatil',
  'computadora',
  'ordenador',
  'casque',
  'ecouteurs',
  'audifonos',
  'auriculares',
  'ecran',
  'pantalla',
  'clavier',
  'teclado',
  'souris',
  'raton',
  'telephone',
  'telefono',
  'celular',
  'montre',
  'reloj',
  'enceinte',
  'altavoz',
  'cherche',
  'busco',
  'quiero',
  'necesito',
  'barato',
  'jeux',
  'juegos',
  'viaje',
  'vuelos',
  'silencieux',
  'silencioso',
  'leger',
  'ligero',
  'quelque',
  'je',
  'une',
  'una',
]);

const strip = (text: string) => text.normalize('NFD').replace(/\p{M}/gu, '');

const PHRASE_PATTERN = new RegExp(
  `(?<![\\p{L}\\p{N}_-])(?:${Object.keys(PHRASES)
    .sort((a, b) => b.length - a.length)
    .map((key) => key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replace(/ /g, "[\\s'’]+"))
    .join('|')})(?![\\p{L}\\p{N}_-])`,
  'giu',
);

/** Whether a request reads as French or Spanish (it uses a word English requests never do). */
export function looksForeign(text: string): boolean {
  return strip(text)
    .toLowerCase()
    .split(/[^a-z]+/)
    .some((word) => FOREIGN_MARKERS.has(word));
}

/**
 * The English words a French or Spanish request means, for the offline parser. Prices are
 * normalized to the "$1500" form: "1 500 $", "1 499,99 $US", "1500 dólares", "US$1,500".
 * With an English locale, only a request that reads as French or Spanish is rewritten.
 */
export function toEnglishRequest(text: string, locale: Locale): string {
  if (locale === 'en' && !looksForeign(text)) return text;
  return (
    strip(text)
      // Elided articles: "l'autonomie", "d'un", "qu'il" → "autonomie", "un", "il".
      .replace(/(?<![\p{L}])(?:l|d|j|qu|n|m|s|t|c)['’](?=\p{L})/giu, (m) =>
        /^j/i.test(m) ? 'je ' : ' ',
      )
      // "1 500" (space, no-break or narrow no-break space as the thousands separator).
      .replace(/(\d)[ \u00a0\u202f](?=\d{3}(?!\d))/g, '$1')
      // "1 499,99 $": a decimal comma before the currency.
      .replace(/(\d),(\d{2})(?=\s*(?:\$|us\$|usd|dollars?|dolares)(?![\p{L}]))/giu, '$1.$2')
      // "US$1,500" → "$1,500".
      .replace(/\bus\s?\$\s*(?=\d)/gi, '$')
      // "1500 $", "1500 $US", "1500 USD", "1500 dólares" → "$1500".
      .replace(
        /(?:\$\s*)?(\d[\d,]*(?:\.\d+)?)\s*(k)?\s*(?:\$\s?(?:us|usd)?|us\$|usd|dollars?|dolares)(?![\p{L}])/giu,
        (_, amount: string, k?: string) => `$${amount}${k ?? ''}`,
      )
      // "16 Go", "1 To" → "16 GB", "1 TB".
      .replace(/(\d+)\s*go\b/gi, '$1 GB')
      .replace(/(\d+)\s*to\b/gi, '$1 TB')
      .replace(PHRASE_PATTERN, (match) => {
        const key = match.toLowerCase().replace(/[\s'’]+/g, ' ');
        return PHRASES[key] ?? match;
      })
      .replace(/[ \t]+/g, ' ')
      .trim()
  );
}
