{{- range $name, $sa := .Values.serviceAccounts }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nixzora.name" (dict "root" $ "component" $name) }}
  labels:
    {{- include "nixzora.labels" (dict "root" $ "component" $name) | nindent 4 }}
  {{- if $sa.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $sa.roleArn | quote }}
  {{- end }}
automountServiceAccountToken: false
---
{{- end }}
