/** Image types accepted for upload, with the file signature ("magic bytes") each must start with. */
export const IMAGE_TYPES = {
  'image/jpeg': {
    ext: 'jpg',
    matches: (b: Buffer) => b.length > 3 && b[0] === 0xff && b[1] === 0xd8 && b[2] === 0xff,
  },
  'image/png': {
    ext: 'png',
    matches: (b: Buffer) =>
      b.length > 8 &&
      b.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])),
  },
  'image/webp': {
    ext: 'webp',
    matches: (b: Buffer) =>
      b.length > 12 &&
      b.toString('ascii', 0, 4) === 'RIFF' &&
      b.toString('ascii', 8, 12) === 'WEBP',
  },
  'image/avif': {
    ext: 'avif',
    matches: (b: Buffer) =>
      b.length > 12 &&
      b.toString('ascii', 4, 8) === 'ftyp' &&
      /^avi[fs]$/.test(b.toString('ascii', 8, 12)),
  },
} as const;

export type ImageContentType = keyof typeof IMAGE_TYPES;

export const CONTENT_TYPE_BY_EXT: Record<string, ImageContentType> = {
  jpg: 'image/jpeg',
  png: 'image/png',
  webp: 'image/webp',
  avif: 'image/avif',
};

/** Storage keys are generated by the server; anything else is rejected (no path traversal). */
export const STORAGE_KEY_PATTERN = /^products\/\d{4}\/\d{2}\/[0-9a-f-]{36}\.(jpg|png|webp|avif)$/;

/**
 * The declared content type is client input. Checking the first bytes stops someone
 * uploading HTML or a script with an image/* label.
 */
export function isDeclaredType(buffer: Buffer, contentType: ImageContentType): boolean {
  return IMAGE_TYPES[contentType].matches(buffer);
}
